import type { AddPageConfig } from "../constant/addPage";

// Users often paste "facebook.com/page" without a protocol.
export const normalizeUrl = (url: string) =>
  /^https?:\/\//.test(url) ? url : `https://${url}`;

// Readable fallback name from the first path segment:
// ".../sunset-market" becomes "Sunset Market".
function nameFromUrl(url: string) {
  try {
    const parsed = new URL(url);
    const slug =
      parsed.pathname.split("/").filter(Boolean)[0] || parsed.hostname;
    return slug
      .replace(/[-_.]+/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase());
  } catch {
    return "New page";
  }
}

// The display name is optional, so an empty one falls back to the URL.
export const resolveName = (config: AddPageConfig) =>
  config.name.trim() || nameFromUrl(normalizeUrl(config.url.trim()));

// Placeholder for the Script Agent's output. Image steps only appear when
// images are enabled, so the script always matches the chosen settings.
export function buildScript(config: AddPageConfig) {
  return [
    "# scout.config · generated by Script Agent",
    `source: ${normalizeUrl(config.url.trim())}`,
    `goal:   "${config.description.trim()}"`,
    "",
    "steps:",
    "  - open(source); scroll_until_loaded()",
    '  - for post in select("[role=article]"):',
    "      extract: text, date, url, reactions",
    ...(config.includeImages
      ? [
          "      extract_images: up to 4 per post",
          "      save_media: original + 480px thumbnail",
        ]
      : []),
    "  - dedupe_by: url",
    `  - limit: ${config.postsPerRun} per run`,
  ].join("\n");
}