import { useState, type KeyboardEvent } from "react";
import DropdownCard from "../../common/dropDownCard";
import { Tag } from "../../common/tags";
import { variantFor } from "./constant/tags";
import { useNavigate } from "react-router-dom";

type Frequency = "15 min" | "30 min" | "Hourly" | "Daily";
const FREQUENCIES: Frequency[] = ["15 min", "30 min", "Hourly", "Daily"];

type MonitoredPage = {
  id: string;
  name: string;
  url: string; // shown without protocol, e.g. "facebook.com/harborcollective"
  avatarClass: string; // Tailwind gradient classes for the avatar tile
  frequency: Frequency;
  postsPerRun: number;
  includeImages: boolean;
  tags: string[];
  paused: boolean;
  lastChecked: string;
};

// Mock data. Replace with your API response once the backend is wired up.
const INITIAL_PAGES: MonitoredPage[] = [
  {
    id: "harbor-collective",
    name: "Harbor Collective",
    url: "facebook.com/harborcollective",
    avatarClass: "from-lime-400 to-green-500",
    frequency: "15 min",
    postsPerRun: 3,
    includeImages: true,
    tags: ["Events", "Local"],
    paused: false,
    lastChecked: "3m ago",
  },
  {
    id: "city-hall-updates",
    name: "City Hall Updates",
    url: "facebook.com/cityhallupdates",
    avatarClass: "from-orange-400 to-yellow-500",
    frequency: "Hourly",
    postsPerRun: 2,
    includeImages: false,
    tags: ["Announcements", "Local"],
    paused: false,
    lastChecked: "just now",
  },
  {
    id: "northwind-coffee",
    name: "Northwind Coffee",
    url: "facebook.com/northwindcoffee",
    avatarClass: "from-lime-400 to-green-500",
    frequency: "Daily",
    postsPerRun: 3,
    includeImages: true,
    tags: ["Promos"],
    paused: false,
    lastChecked: "just now",
  },
];

// Placeholder for the script the Script Agent generates server-side. Built
// from the current settings so the panel reflects slider/toggle changes.
function buildScript(page: MonitoredPage) {
  return [
    "# scout.config · generated by Script Agent",
    `source: https://www.${page.url}`,
    'goal:   "New posts and announcements"',
    "",
    "steps:",
    "  - open(source); scroll_until_loaded()",
    '  - for post in select("[role=article]"):',
    "      extract: text, date, url, reactions",
    ...(page.includeImages
      ? [
          "      extract_images: up to 4 per post",
          "      save_media: original + 480px thumbnail",
        ]
      : []),
    "  - dedupe_by: url",
    `  - limit: ${page.postsPerRun}`,
  ].join("\n");
}

const FIELD_LABEL =
  "text-[11px] font-semibold uppercase tracking-wider text-stone-400";

// Expanded content of one card. It is a separate component so each card
// keeps its own tag-input draft instead of sharing one at page level.
function PageSettings({
  page,
  onChange,
  onRemove,
}: {
  page: MonitoredPage;
  onChange: (patch: Partial<MonitoredPage>) => void;
  onRemove: () => void;
}) {
  const [draft, setDraft] = useState("");

  function addTag() {
    const label = draft.trim();
    setDraft("");
    // Ignore empty input and case-insensitive duplicates.
    if (
      !label ||
      page.tags.some((t) => t.toLowerCase() === label.toLowerCase())
    )
      return;
    onChange({ tags: [...page.tags, label] });
  }

  function handleTagKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      e.preventDefault();
      addTag();
    }
  }

  return (
    <div className="grid gap-6 md:grid-cols-[1fr_340px]">
      {/* Left: read-only script preview */}
      <div className="flex flex-col gap-2">
        <span className={FIELD_LABEL}>Script</span>
        <pre className="h-64 overflow-auto rounded-xl bg-stone-900 p-4 font-mono text-xs leading-relaxed text-stone-100">
          {buildScript(page)}
        </pre>
      </div>

      {/* Right: editable settings */}
      <div className="flex flex-col gap-5">
        <div className="flex flex-col gap-2">
          <label htmlFor={`freq-${page.id}`} className={FIELD_LABEL}>
            Frequency
          </label>
          <select
            id={`freq-${page.id}`}
            value={page.frequency}
            onChange={(e) =>
              onChange({ frequency: e.target.value as Frequency })
            }
            className="h-11 rounded-xl border border-orange-100 bg-orange-50/60 px-3 text-sm text-stone-700 focus:outline-none focus:ring-2 focus:ring-orange-300"
          >
            {FREQUENCIES.map((f) => (
              <option key={f} value={f}>
                {f}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-col gap-2">
          <label htmlFor={`posts-${page.id}`} className={FIELD_LABEL}>
            Posts per run:{" "}
            <span className="text-stone-700">{page.postsPerRun}</span>
          </label>
          <input
            id={`posts-${page.id}`}
            type="range"
            min={1}
            max={10}
            value={page.postsPerRun}
            onChange={(e) => onChange({ postsPerRun: Number(e.target.value) })}
            className="accent-orange-700"
          />
        </div>

        <div className="flex items-center gap-3">
          <button
            type="button"
            role="switch"
            aria-checked={page.includeImages}
            aria-label="Include images"
            onClick={() => onChange({ includeImages: !page.includeImages })}
            className={`relative h-6 w-11 rounded-full transition-colors ${
              page.includeImages ? "bg-emerald-600" : "bg-stone-300"
            }`}
          >
            <span
              className={`absolute top-0.5 left-0.5 h-5 w-5 rounded-full bg-white shadow transition-transform ${
                page.includeImages ? "translate-x-5" : ""
              }`}
            />
          </button>
          <span className="text-sm text-stone-700">Include images</span>
        </div>

        <div className="flex flex-col gap-2">
          <span className={FIELD_LABEL}>Tags</span>
          <div className="flex flex-wrap items-center gap-2 rounded-xl border border-orange-100 bg-orange-50/60 p-3">
            {page.tags.map((tag) => (
              <Tag
                key={tag}
                label={tag}
                variant={variantFor(tag)}
                onRemove={() =>
                  onChange({ tags: page.tags.filter((t) => t !== tag) })
                }
              />
            ))}
            <input
              type="text"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={handleTagKeyDown}
              placeholder="Add tag, press Enter"
              className="min-w-[140px] flex-1 bg-transparent text-sm text-stone-700 placeholder:text-stone-400 focus:outline-none"
            />
          </div>
        </div>

        <div className="flex flex-wrap gap-3">
          <button
            type="button"
            onClick={() => onChange({ paused: !page.paused })}
            className="h-11 rounded-xl border border-stone-200 bg-white px-5 text-sm font-medium text-stone-700 transition hover:bg-stone-50"
          >
            {page.paused ? "Resume monitoring" : "Pause monitoring"}
          </button>
          <button
            type="button"
            onClick={onRemove}
            className="h-11 rounded-xl border border-red-200 bg-white px-5 text-sm font-medium text-red-500 transition hover:bg-red-50"
          >
            Remove
          </button>
        </div>
      </div>
    </div>
  );
}

export default function Scoutline_MonitoredPage() {
  const [pages, setPages] = useState<MonitoredPage[]>(INITIAL_PAGES);
  const navigate = useNavigate();
  // Counts shown under the title; "live" means not paused.
  const liveCount = pages.filter((p) => !p.paused).length;

  // Every control edits one page by id, so a single patch helper covers
  // frequency, slider, toggle, tags and pause.
  function updatePage(id: string, patch: Partial<MonitoredPage>) {
    setPages((prev) => prev.map((p) => (p.id === id ? { ...p, ...patch } : p)));
  }

  function removePage(id: string) {
    setPages((prev) => prev.filter((p) => p.id !== id));
  }

  return (
    <div className="min-h-full bg-gradient-to-br from-orange-50 via-[#fffaf5] to-[#fffaf5] p-8">
      <div className="mx-auto flex max-w-4xl flex-col gap-6">
        <header className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-extrabold text-stone-800">
              Monitored pages
            </h1>
            <p className="mt-1 text-sm text-stone-400">
              {pages.length} monitored · {liveCount} live
            </p>
          </div>
          {/* Wire this to your add-page flow (modal or route). */}
          <button
            type="button"
            className="rounded-xl bg-orange-700 px-5 py-2.5 text-sm font-semibold text-white shadow-md transition hover:bg-orange-800"
            onClick={() => navigate("/addPage")}
          >
            + Add page
          </button>
        </header>

        <div className="flex flex-col gap-4">
          {pages.map((page, index) => (
            <DropdownCard
              key={page.id}
              // First card starts open, like the screenshot.
              defaultOpen={index === 0}
              title={page.name}
              subtitle={page.url}
              avatar={
                <div
                  className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br font-bold text-white ${page.avatarClass}`}
                >
                  {page.name[0]}
                </div>
              }
              tags={page.tags.map((tag) => (
                <Tag key={tag} label={tag} variant={variantFor(tag)} />
              ))}
              meta={[
                page.frequency,
                `${page.postsPerRun}/run`,
                ...(page.includeImages ? ["images"] : []),
              ]}
              status={
                <div className="min-w-[96px] text-xs text-stone-500">
                  <p className="flex items-center gap-1.5 font-medium text-stone-700">
                    <span
                      className={`h-2 w-2 rounded-full ${
                        page.paused ? "bg-stone-400" : "bg-emerald-600"
                      }`}
                    />
                    {page.paused ? "Paused" : "Live"}
                  </p>
                  <p>
                    {page.paused
                      ? "not monitoring"
                      : `checked ${page.lastChecked}`}
                  </p>
                </div>
              }
            >
              <PageSettings
                page={page}
                onChange={(patch) => updatePage(page.id, patch)}
                onRemove={() => removePage(page.id)}
              />
            </DropdownCard>
          ))}
        </div>
      </div>
    </div>
  );
}
